LANG_pl = {"title": "Twój sekretarz / Urzędnik 2.0",}

LANG_eng = {
    "title": "Personal assistant / Clerk 2.0",
    "new_pro": "Create New Project",
    "open_pro": "Open Project",
    "add_folder": "Add Folder",
    "add_files": "Add Files",
    "add_links": "Add Sources",
    "manage_links": "Manage Sources (URLs/Info)",
    "assign_sources": "Assign Sources",
    "input_links": "Paste Links or Descriptions for Screenshots\nNew Line (Enter) Separates Successive Links/Desc",
    "list_files": "List Files",
    "labels": "Labels",
    "del_pro": "Delete Project",
    "filter_labels": "Filter Labels",
    "sel_dir": "Select Directory",
    "proj_name": "Project Name:",
    "proj_local": "Project will be saved in:",
    "go_back": "Go Back",
    "quit": "Quit",
    "error": "Error!",
    "wrong_dir_name": "Wrong directory name! No < > : \" / \\ | ? * allowed.",
    "dir_exists": "Dir or file with that name already exists! Try different name.",
    "lack_of_base_file": "It's not a project directory! A directory must include base.json file.",
    "no_files": "No files or directories added to the project.",
    "id": "ID + File name",
    "f_name": "File name",
    "source": "Source",
    "path": "Path",
    "c_time": "Creation time",
    "add_f_copy_files": "Updating project and copying files. I'll let you know when I'm finished :)",
    "update_copy_finish": "Updating project and copying files finished. Total files added: ",
    "no_files_added": "Something went wrong: No files added.",
    "submit": "Submit",
    "no_links_or_wrong": "Wrong links or no links!",
    'source_added': "Total number of sources has been added: ",
    "show_all_links": "Show all sources in the project",
    "show_unassigned_links": "Show only unassigned sources",
    "assign": "Assign Source to Image",
    "mark_sources_and_img": "Mark Source and Image to Assign",
    "ask_assign": "Do you want to assign Source to Image?",
    "ask_save_changes": "Do you want to save changes?",
    "no_changes_applied": "No changes applied. Nothing to save.",
    "save_changes": "Save Changes",
    "del_source": "Delete Source",
    "no_source_sel": "No Source Selected",
    "save_to_confirm_del": "Save to confirm deletion",
    "f_rename": "Rename File",
    "s_rename": "Rename Source",
    "manage_labels": "Manage Labels",
    "comment": "Comment",
    "extra_fields": "Extra Fields",
    "alter_comment": "Alter Comment",
    "del_file": "Delete File",
    "manage_fields": "Manage Fields",
    "input_new_label": "Input new Label:",
    "add_label": "Add Label",
    "del_label": "Delete Label",
    "edit_label": "Edit Label",
    "no_labels": "Empty string or Label already added",
    "no_label_selected": "No Label selected",
    "ask_del_conf_1": "This operation will affect: ",
    "ask_del_conf_2": " file(s).\nAre you sure you want to delete the Label:\n",
    "rename_label": "Rename Label: ",
    "ask_edit_conf_1": "This operation will affect: ",
    "ask_edit_conf_2": " file(s).\nAre you sure you want to edit the Label:\n",
    "no_new_label_name": "Input a new Label name",
    "label_man": "Label management for: ",
    "sel_lbl": "Select Label",
    "remove_lbl": "Remove Label",
    "confirm_sel": "Save Changes",
    "go_to_labels": "Go to Label Manager",
    "all_lbls": "All Labels in the Project",
    "file_lbls": "Labels related to the File",
    "sel_lbls_incl": "Select Labels to Include",
    "sel_lbls_excl": "Select Labels to Exclude",
    "show_all": "Show all",
    "update": "Update",
    "filter": "Filter",
    "add_field": "Add Field",
    "edit_field": "Edit Field",
    "del_field": "Delete Field",
    "curr_field": "Current Field: ",
    "field_name": "Field name",
    "field_val": "Field value",
    "same_comment": "New Comment looks exactly like the previous one",
    "same_source": "New Source looks exactly like the previous one",
    "same_f_name": "New File name looks exactly like the previous one",
    "f_name_wrong_suffix": "New File name has a different suffix. Keep the same file extension to prevent incompatibility.",
    "fields_manager": "Fields Manager",
    "rename_field": "Rename Field",
    "change_val_field": "Change Field value",
    "bind_manager": "Binding Manager",
    "show_binds": "Show binds for selected file",
    "bind_parent": "Bind as Parent to",
    "bind_child": "Bind as Child to",
    "bind_sibling": "Bind as Sibling to",
    "unbind_parent_child": "Unbind as Parent/Child",
    "unbind_sibling": "Unbind as Sibling",
    "show_all_binds": "Show all binds",
    "select_file_item": "Select File from center pan",
    "no_binds": "No binds to show",
    "select_files_to_bind": "Select Files from center pan and right pan"
}
LANG = LANG_eng
