LANG_pl = {
    "title": "Twój sekretarz / Urzędnik 2.0", 
    "new_pro": "Zacznij nowy Projekt",
    "open_pro": "Otwórz projekt",
    "add_folder": "Dodaj folder ze plikami",
    "add_files": "Dodaj pliki do Projektu",
    "settings": "Ustawienia",
    "add_links": "Dodaj źródła",
    "manage_links": "Zarządzaj źródłami (Linki/Info)",
    "assign_sources": "Przypisz źródło",
    "input_links": "Wklej linki lub opisy do plików\nNowy wiersz (Enter) powoduje oddzielenie kolejnych linków/opisów",
    "list_files": "Wylistuj pliki z folderu",
    "labels": "Tagi",
    "del_pro": "Usuń Projekt",
    "filter_labels": "Filtruj Tagi",
    "sel_dir": "Wybierz folder",
    "proj_name": "Nazwa Projektu:",
    "proj_local": "Projekt zostanie zapisany w:",
    "go_back": "Wróć",
    "quit": "Zamknij",
    "error": "Błąd!",
    "wrong_dir_name": "Błędna nazwa folderu! Znaki < > : \" / \\ | ? * nie są dozwolone.",
    "dir_exists": "Folder lub plik o tej nazwie już istnieje! Podaj inną nazwę.",
    "lack_of_base_file": "To nie jest folder z Projektem! Folder musi zawierać plik 'base.json'",
    "no_files": "Żadne pliki lub foldery nie zostały dodane do Projektu",
    "id": "ID + nazwa",
    "f_name": "Nazwa",
    "source": "Źródło",
    "path": "Ścieżka",
    "c_time": "Utworzony",
    "add_f_copy_files": "Aktualizacja Projektu i kopiowanie plików. Dam znać kiedy skończę :)",
    "update_copy_finish": "Aktualizacja Projektu i kopiowanie plików zakończone. łącznie plików dodanych: ",
    "no_files_added": "Coś poszło nie tak: nie dodano plików.",
    "submit": "OK",
    "no_links_or_wrong": "Błędny link lub brak linku!",
    'source_added': "Łączna liczba dodanych źródeł: ",
    "show_all_links": "Pokaż wszystkie źródła w Projekcie",
    "show_unassigned_links": "Pokaż źródła nieprzypisane",
    "assign": "Przypisz źródło do pliku",
    "mark_sources_and_img": "Zaznacz źródło i plik do przypisania",
    "ask_assign": "Czy chcesz przypisać źródło do pliku?",
    "ask_save_changes": "Zapisać zmiany?",
    "no_changes_applied": "Brak zmian do wprowadzenia.",
    "save_changes": "Zapisz zmiany",
    "del_source": "Usuń źródło",
    "no_source_sel": "Wybierz źródło",
    "save_to_confirm_del": "Zapisz aby potwierdzić usunięcie",
    "f_rename": "Zmień nazwę",
    "s_rename": "Zmień źródło",
    "manage_labels": "Zarządzaj tagami",
    "comment": "Komentarz",
    "extra_fields": "Pola dodatkowe",
    "alter_comment": "Zmień komentarz",
    "del_file": "Usuń plik",
    "del_file_confirm": "Usunąć plik?",
    "binds_affected": "Binds affected: ",
    "manage_fields": "Zarządzaj polami",
    "input_new_label": "Wprowadź nowy Tag:",
    "add_label": "Dodaj Tag",
    "del_label": "Usuń Tag",
    "edit_label": "Zmień Tag",
    "no_labels": "Brak Tagu lub Tag już istnieje",
    "no_label_selected": "Wybierz Tag",
    "ask_del_conf_1": "Ta operacja wpłynie na ",
    "ask_del_conf_2": " plik/ów.\nUsunąć Tag:\n",
    "rename_label": "Nazwij Tag: ",
    "ask_edit_conf_1": "Ta operacja wpłynie na : ",
    "ask_edit_conf_2": " plik/ów.\nZmienić Tag:\n",
    "no_new_label_name": "Wprowadź nowy Tag",
    "label_man": "Label management for: ",
    "sel_lbl": "Select Label",
    "remove_lbl": "Remove Label",
    "confirm_sel": "Save Changes",
    "go_to_labels": "Go to Label Manager",
    "all_lbls": "All Labels in the Project",
    "file_lbls": "Labels related to the File",
    "sel_lbls_incl": "Select Labels to Include",
    "sel_lbls_excl": "Select Labels to Exclude",
    "show_all": "Show all",
    "update": "Update",
    "filter": "Filter",
    "add_field": "Add Field",
    "edit_field": "Edit Field",
    "del_field": "Delete Field",
    "curr_field": "Current Field: ",
    "field_name": "Field name",
    "field_val": "Field value",
    "same_comment": "New Comment looks exactly like the previous one",
    "same_source": "New Source looks exactly like the previous one",
    "same_f_name": "New File name looks exactly like the previous one",
    "f_name_wrong_suffix": "New File name has a different suffix. Keep the same file extension to prevent incompatibility.",
    "fields_manager": "Fields Manager",
    "rename_field": "Rename Field",
    "change_val_field": "Change Field value",
    "bind_manager": "Binding Manager",
    "show_binds": "Show binds for selected file",
    "bind_parent": "Bind as Parent to",
    "bind_child": "Bind as Child to",
    "bind_sibling": "Bind as Sibling to",
    "unbind_parent_child": "Unbind as Parent/Child",
    "unbind_sibling": "Unbind as Sibling",
    "show_all_binds": "Show all binds",
    "select_file_item": "Select File from center pan",
    "no_binds": "No binds to show",
    "select_files_to_bind": "Select Files from center pan and right pan",
    "or_include": "'OR' operator between Labels to include",
    "and_include": "'AND' operator between Labels to include",
    "or_exclude": "'OR' operator between Labels to exclude",
    "and_exclude": "'AND' operator between Labels to exclude",
    "dist_manager": "Distribute Label Manager",
    "open_default_viewer": "Open in default viewer",
    "open_in_new_detail_pan": "Open in new detail pan",
    "move_up": "Move up",
    "move_down": "Move down",
    "open_src_browser": "Open Src in Browser",
    "open_file_in_def": "Open File in Default",
    "add_labels": "Add Label(s)",
    "rem_labels": "Remove Label(s)",
    "file_history": "File History",
    "proj_hist": "Project History",
    "lbl_pan": "Label Pan",
    "filter_pan": "Filter Pan",
    "distr_man": "Distribute",
    "lbls_in_pro": "Labels in the project",
    "add_lbl_to_project": "Add Label to\nthe Project",
    "remane_lbl": "Rename Label",
    "del_lbl": "Delete Label",
    "type_lbl_name": "Type in a new label name:",
    "add_lbl_to_pro": "Add Label to the Project",
    "msg_message_delete": "Are you sure you want to delete ",
    "restore": "Restore",
    "sel_labels": "Select Labels",
    "info_text": """What is all about?
        The main idea is to create combinations of labels. 
        Then the program will copy all files linked to created combinations to dedicated directories and return a report with file's data.
        How it works:
        Select Label(s) and push them to Combined Labels.
        Check if combination is ok and push them to Folders.
        Beware: if a combination consists of at least two labels a logical operator between them is OR.
        Rename Folders or keep default names. If all folders are ready choose Prepare Distribution.
        Before preparing Distribution you can save current settings by choosing Save Schema""",
    "push_sel_labels": "Push selected Labels",
    "save_schema": "Save schema",
    "load_schema": "Load schema",
    "comb_labels": "Combined Labels",
    "push_all_lbls_to_folders": "Push all combined Labels to Folders",
    "push_lbl_to_folders": "Push combined Label to Folders",
    "del_comb": "Delete combination",
    "folder": "Folder",
    "rename_folder": "Rename Folder",
    "prep_dist": "Prepare Distribution",
    "del_folder": "Delete folder",
    "operation_will_affect": "This operation will affect Folder: ",
    "rename_": "Rename ",
    "prep_folders_first": "Prepare Folders first",
    "create_files_list": "Create Files list",
    "create_folders_and_files_list": "Create Folders and Files list",
    "create_folder": "Create folder",
    "create_report_file": "Create Report file - xlsx extension is fixed",
    "files_rep_saved": "Files and Report saved!",
    "save_as": "Save as",
    "rep_saved": "Report saved!",
    "schema_name": "Schema name:",
    "del_schema": "Delete schema",
    "unable_to_save": "Unable to save",
    "schema_exists": "Schema with this name already exists",
    "distributor": "Distributor"
}

LANG_eng = {
    "title": "Personal assistant / Clerk 2.0",
    "new_pro": "Create New Project",
    "open_pro": "Open Project",
    "add_folder": "Add Folder",
    "add_files": "Add files to project",
    "settings": "Settings",
    "add_links": "Add Sources",
    "manage_links": "Manage Sources (URLs/Info)",
    "assign_sources": "Assign Sources",
    "input_links": "Paste Links or Descriptions for Screenshots\nNew Line (Enter) Separates Successive Links/Desc",
    "list_files": "List Files",
    "labels": "Labels",
    "del_pro": "Delete Project",
    "filter_labels": "Filter Labels",
    "sel_dir": "Select Directory",
    "proj_name": "Project Name:",
    "proj_local": "Project will be saved in:",
    "go_back": "Go Back",
    "quit": "Quit",
    "error": "Error!",
    "wrong_dir_name": "Wrong directory name! No < > : \" / \\ | ? * allowed.",
    "dir_exists": "Dir or file with that name already exists! Try different name.",
    "lack_of_base_file": "It's not a project directory! A directory must include base.json file.",
    "no_files": "No files or directories added to the project.",
    "id": "ID + File name",
    "f_name": "File name",
    "source": "Source",
    "path": "Path",
    "c_time": "Creation time",
    "add_f_copy_files": "Updating project and copying files. I'll let you know when I'm finished :)",
    "update_copy_finish": "Updating project and copying files finished. Total files added: ",
    "no_files_added": "Something went wrong: No files added.",
    "submit": "Submit",
    "no_links_or_wrong": "Wrong links or no links!",
    'source_added': "Total number of sources has been added: ",
    "show_all_links": "Show all sources in the project",
    "show_unassigned_links": "Show only unassigned sources",
    "assign": "Assign Source to Image",
    "mark_sources_and_img": "Mark Source and Image to Assign",
    "ask_assign": "Do you want to assign Source to Image?",
    "ask_save_changes": "Do you want to save changes?",
    "no_changes_applied": "No changes applied. Nothing to save.",
    "save_changes": "Save Changes",
    "del_source": "Delete Source",
    "no_source_sel": "No Source Selected",
    "save_to_confirm_del": "Save to confirm deletion",
    "f_rename": "Rename File",
    "s_rename": "Rename Source",
    "manage_labels": "Manage Labels",
    "comment": "Comment",
    "extra_fields": "Extra Fields",
    "alter_comment": "Alter Comment",
    "del_file": "Delete File",
    "del_file_confirm": "Are you sure you want delete this File (this operation is irreversible and affects binds): ",
    "binds_affected": "Binds affected: ",
    "manage_fields": "Manage Fields",
    "input_new_label": "Input new Label:",
    "add_label": "Add Label",
    "del_label": "Delete Label",
    "edit_label": "Edit Label",
    "no_labels": "Empty string or Label already added",
    "no_label_selected": "No Label selected",
    "ask_del_conf_1": "This operation will affect: ",
    "ask_del_conf_2": " file(s).\nAre you sure you want to delete the Label:\n",
    "rename_label": "Rename Label: ",
    "ask_edit_conf_1": "This operation will affect: ",
    "ask_edit_conf_2": " file(s).\nAre you sure you want to edit the Label:\n",
    "no_new_label_name": "Input a new Label name",
    "label_man": "Label management for: ",
    "sel_lbl": "Select Label",
    "remove_lbl": "Remove Label",
    "confirm_sel": "Save Changes",
    "go_to_labels": "Go to Label Manager",
    "all_lbls": "All Labels in the Project",
    "file_lbls": "Labels related to the File",
    "sel_lbls_incl": "Select Labels to Include",
    "sel_lbls_excl": "Select Labels to Exclude",
    "show_all": "Show all",
    "update": "Update",
    "filter": "Filter",
    "add_field": "Add Field",
    "edit_field": "Edit Field",
    "del_field": "Delete Field",
    "curr_field": "Current Field: ",
    "field_name": "Field name",
    "field_val": "Field value",
    "same_comment": "New Comment looks exactly like the previous one",
    "same_source": "New Source looks exactly like the previous one",
    "same_f_name": "New File name looks exactly like the previous one",
    "f_name_wrong_suffix": "New File name has a different suffix. Keep the same file extension to prevent incompatibility.",
    "fields_manager": "Fields Manager",
    "rename_field": "Rename Field",
    "change_val_field": "Change Field value",
    "bind_manager": "Binding Manager",
    "show_binds": "Show binds for selected file",
    "bind_parent": "Bind as Parent to",
    "bind_child": "Bind as Child to",
    "bind_sibling": "Bind as Sibling to",
    "unbind_parent_child": "Unbind as Parent/Child",
    "unbind_sibling": "Unbind as Sibling",
    "show_all_binds": "Show all binds",
    "select_file_item": "Select File from center pan",
    "no_binds": "No binds to show",
    "select_files_to_bind": "Select Files from center pan and right pan",
    "or_include": "'OR' operator between Labels to include",
    "and_include": "'AND' operator between Labels to include",
    "or_exclude": "'OR' operator between Labels to exclude",
    "and_exclude": "'AND' operator between Labels to exclude",
    "dist_manager": "Distribute Label Manager",
    "open_default_viewer": "Open in default viewer",
    "open_in_new_detail_pan": "Open in new detail pan",
    "move_up": "Move up",
    "move_down": "Move down",
    "open_src_browser": "Open Src in Browser",
    "open_file_in_def": "Open File in Default",
    "add_labels": "Add Label(s)",
    "rem_labels": "Remove Label(s)",
    "file_history": "File History",
    "proj_hist": "Project History",
    "lbl_pan": "Label Pan",
    "filter_pan": "Filter Pan",
    "distr_man": "Distribute",
    "lbls_in_pro": "Labels in the project",
    "add_lbl_to_project": "Add Label to\nthe Project",
    "remane_lbl": "Rename Label",
    "del_lbl": "Delete Label",
    "type_lbl_name": "Type in a new label name:",
    "add_lbl_to_pro": "Add Label to the Project",
    "msg_message_delete": "Are you sure you want to delete ",
    "restore": "Restore",
    "sel_labels": "Select Labels",
    "info_text": """What is all about?
        The main idea is to create combinations of labels. 
        Then the program will copy all files linked to created combinations to dedicated directories and return a report with file's data.
        How it works:
        Select Label(s) and push them to Combined Labels.
        Check if combination is ok and push them to Folders.
        Beware: if a combination consists of at least two labels a logical operator between them is OR.
        Rename Folders or keep default names. If all folders are ready choose Prepare Distribution.
        Before preparing Distribution you can save current settings by choosing Save Schema""",
    "push_sel_labels": "Push selected Labels",
    "save_schema": "Save schema",
    "load_schema": "Load schema",
    "comb_labels": "Combined Labels",
    "push_all_lbls_to_folders": "Push all combined Labels to Folders",
    "push_lbl_to_folders": "Push combined Label to Folders",
    "del_comb": "Delete combination",
    "folder": "Folder",
    "rename_folder": "Rename Folder",
    "prep_dist": "Prepare Distribution",
    "del_folder": "Delete folder",
    "operation_will_affect": "This operation will affect Folder: ",
    "rename_": "Rename ",
    "prep_folders_first": "Prepare Folders first",
    "create_files_list": "Create Files list",
    "create_folders_and_files_list": "Create Folders and Files list",
    "create_folder": "Create folder",
    "create_report_file": "Create Report file - xlsx extension is fixed",
    "files_rep_saved": "Files and Report saved!",
    "save_as": "Save as",
    "rep_saved": "Report saved!",
    "schema_name": "Schema name:",
    "del_schema": "Delete schema",
    "unable_to_save": "Unable to save",
    "schema_exists": "Schema with this name already exists",
    "distributor": "Distributor"
}

LANG = LANG_eng
