LANG_pl = {
    "title": "Twój sekretarz / Urzędnik 2.0",
    "new_pro": "Zacznij nowy Projekt",
    "open_pro": "Otwórz projekt",
    "quit": "Zamknij",
    "file": "Plik",
    "new_pro_info": "Zacznij nowy Projekt\nWybierz lokalizację folderu, w którym chcesz pracować\n(najlepiej załóż nowy katalog w folderze z programem)\nPamiętaj, że nazwa katalogu będzie również nazwą Projektu.",
    "sel_location": "Wybierz lokalizację: ",
    "chang_location": "Zmień lokalizację",
    "go_back": "Wróć",
    "sel_dir": "Wybierz folder",
    "proj_name": "Nazwa Projektu:",
    "proj_local": "Projekt zostanie zapisany w:",
    "pro_already_created": "Projekt już istnieje w tej lokalizacji.",
    "pro_already_created_msg": "Usuń projekt w tej lokalizacji i dopiero wtedy załóż nowy.",
    "path_exists": "Ścieżka istnieje.",
    "path_exists_msg": "Czy chcesz utworzyć projekt w tym folderze?",
    "wrong_path": "Wybierz ścieżkę do katalogu",
    "wrong_path_msg": "Wybrana ścieżka prowadzi do pliku a nie do katalogu.",
    "wrong_path_name": "Błędna nazwa w ścieżce.",
    "wrong_path_name_msg": "Błędna nazwa w ścieżce. Niektóre znaki moga być niedozwolone (sprawdź i usuń: < > : \" / \\ | ? *).",
    "Unable_to_save": "Problem z zapisem plików we wskazanym folderze",
    "Unable_to_save_msg": "Folder zawierał już pliki konieczne do założenia projektu. Usuń je lub utwóz projekt w innym folderze",
    "add_files": "Dodaj pliki do Projektu",
    "add_folder": "Dodaj folder z plikami",
    "sel_project": "Wybrany projekt:",
    "browse": "Przeglądaj",
    "sel_dir_proj": "Wybierz katalog z projektem",
    "add_files_from_dir": "Dodaj pliki z wybranego katalogu",
    "add_selected_files": "Dodaj wybrane pliki",
    "options": "Opcje",
    "copy_all_files": "Kopiuj wszystkie pliki",
    "copy_only": "Kopiuj tylko pliki z rozszerzeniami .jpg, .jpeg, .png. (Resztę ignoruj) ",
    "sel_dir_with_files": "Wybierz folder z plikami do dodania",
    "wrong_path_2": "Błędna ścieżka",
    "wrong_path_2_msg": "Podaj ścieżkę 'absolutną', np. C:\\My documents\\Files...",
    "wrong_path_2_msg_2": "Podany plik nie jest katalogiem. Czy chcesz dodać pliki z katalogu",
    "confirm": "Potwierdź operację",
    "confirm_msg": "Potwierdź aby rozpoczać kopiowanie plików. Operacja może potrwać kilka minut w zależności od ilości pilków.",
    "Files_added": "Dodane pliki",
    "Files_added_msg": " plik(ów) dodanych do projektu",
    "circ_ref": "Odniesienie okrężne",
    "circ_ref_msg": "Stwierdzono odniesienie okrężne: Próbujesz dodać do projektu katalog, w którym jest projekt.\nOperacja niemożliwa.",
    "choose_file": "Wybierz plik z listy powyżej",
    "del_file": "Usuń plik",
    "open_default_viewer": "Otwórz w domyślnym",
    "f_name": "Nazwa",
    "source": "Źródło",
    "path": "Ścieżka",
    "labels": "Tagi",
    "comment": "Komentarz",
    "c_time": "Utworzony",
    "f_rename": "Zmień nazwę",
    "s_rename": "Zmień źródło",
    "manage_labels": "Zarządzaj tagami",
    "alter_comment": "Zmień komentarz",
    "same_comment": "Nowy Komentarz wygląda tak samo jak poprzedni",
    "same_source": "Nowe Źródło wygląda tak samo jak poprzedni",
    "same_f_name": "Nowa nazwa Pliku wygląda tak samo jak poprzednia",
    "f_name_wrong_suffix": "Nowa nazwa Pliku ma inne rozszerzenie. Zachowaj to samo rozszerzenie by zapobiec błędom.",
    "open_src_browser": "Otwórz Źr. w przegl.",
    "move_up": "Do góry",
    "move_down": "Do dołu",
    "add_labels": "Dodaj Tag(i)",
    "rem_labels": "Usuń Tag(i)",
    "file_history": "Historia Pliku",
    "proj_hist": "Historia Projektu",
    "record": "Wpis",
    "restore": "Przywróć",
    "lbls_in_pro": "Tagi w Projekcie",
    "add_lbl_to_project": "Dodaj Tag\ndo Projektu",
    "remane_lbl": "Zmień nazwę",
    "del_lbl": "Usuń Tag",
    "type_lbl_name": "Podaj nową nazwę Tagu:",
    "add_lbl_to_pro": "Dodaj Tag do Projektu",
    "msg_message_delete": "Potwierdź usunięcie  ",
    "or_include": "operator 'LUB' między Tagami do włączenia",
    "and_include": "operator 'I' między Tagami do włączenia",
    "or_exclude": "'operator 'LUB' między Tagami do wyłączenia",
    "and_exclude": "operator 'I' między Tagami do wyłączenia",
    "manage_sources": "Zarządzaj źródłami",
    "Available_formats": "Obsługiwane formaty graficzne: .jpg, .jpeg, .png\nSpróbuj otworzyć w domyślnym programie",
    "Pass_sources": "Wprowadź źródła aby dodać je do projektu",
    "insert_sources": "Wklej źródła przedzielone enterem (jedno pod drugim)",
    "add_sources": "Dodaj źródła do projektu",
    "del_source_pro": "Usun źródło z projektu",
    "add_source": "Dodaj źródło",
    "del_source": "Usuń źródło",
    "look_up": "Wyszukaj",

    "settings": "Ustawienia",
    "add_links": "Dodaj źródła",
    "manage_links": "Zarządzaj źródłami (Linki/Info)",
    "assign_sources": "Przypisz źródło",
    "input_links": "Wklej linki lub opisy do plików\nNowy wiersz (Enter) powoduje oddzielenie kolejnych linków/opisów",
    "list_files": "Wylistuj pliki z folderu",
    "del_pro": "Usuń Projekt",
    "filter_labels": "Filtruj Tagi",
    "error": "Błąd!",
    "wrong_dir_name": "Błędna nazwa folderu! Znaki < > : \" / \\ | ? * nie są dozwolone.",
    "dir_exists": "Folder lub plik o tej nazwie już istnieje! Podaj inną nazwę.",
    "lack_of_base_file": "To nie jest folder z Projektem! Folder musi zawierać plik 'base.json'",
    "no_files": "Żadne pliki lub foldery nie zostały dodane do Projektu",
    "add_f_copy_files": "Aktualizacja Projektu i kopiowanie plików. Dam znać kiedy skończę :)",
    "update_copy_finish": "Aktualizacja Projektu i kopiowanie plików zakończone. łącznie plików dodanych: ",
    "no_files_added": "Coś poszło nie tak: nie dodano plików.",
    "submit": "OK",
    "no_links_or_wrong": "Błędny link lub brak linku!",
    'source_added': "Łączna liczba dodanych źródeł: ",
    "show_all_links": "Pokaż wszystkie źródła w Projekcie",
    "show_unassigned_links": "Pokaż źródła nieprzypisane",
    "assign": "Przypisz źródło do pliku",
    "mark_sources_and_img": "Zaznacz źródło i plik do przypisania",
    "ask_assign": "Czy chcesz przypisać źródło do pliku?",
    "ask_save_changes": "Zapisać zmiany?",
    "no_changes_applied": "Brak zmian do wprowadzenia.",
    "save_changes": "Zapisz zmiany",
    "no_source_sel": "Wybierz źródło",
    "save_to_confirm_del": "Zapisz aby potwierdzić usunięcie",
    "extra_fields": "Pola dodatkowe",
    "del_file_confirm": "Usunąć plik?",
    "binds_affected": "Binds affected: ",
    "manage_fields": "Zarządzaj polami",
    "input_new_label": "Wprowadź nowy Tag:",
    "add_label": "Dodaj Tag",
    "del_label": "Usuń Tag",
    "edit_label": "Zmień Tag",
    "no_labels": "Brak Tagu lub Tag już istnieje",
    "no_label_selected": "Wybierz Tag",
    "ask_del_conf_1": "Ta operacja wpłynie na ",
    "ask_del_conf_2": " plik/ów.\nUsunąć Tag:\n",
    "rename_label": "Nazwij Tag: ",
    "ask_edit_conf_1": "Ta operacja wpłynie na : ",
    "ask_edit_conf_2": " plik/ów.\nZmienić Tag:\n",
    "no_new_label_name": "Wprowadź nowy Tag",
    "label_man": "Label management for: ",
    "sel_lbl": "Wybierz Tag",
    "remove_lbl": "Usuń Tag",
    "confirm_sel": "Zapisz",
    "go_to_labels": "Idź do Menagera",
    "all_lbls": "Dodaj Tag do Projektu",
    "file_lbls": "Tagi powiązane z Plikiem",
    "sel_lbls_incl": "Wybierz Tagi do Włączenia",
    "sel_lbls_excl": "Wybierz Tagi do Wyłączenia",
    "show_all": "Pokaż wszystko",
    "update": "Aktualizuj",
    "filter": "Filtruj",
    "add_field": "Dodaj Pole",
    "edit_field": "Edytuj Pole",
    "del_field": "Usuń Pole",
    "curr_field": "Zaznaczone Pole: ",
    "field_name": "Nazwa",
    "field_val": "Wartość",

    "fields_manager": "Manager Pół",
    "rename_field": "Zmień nazwę Pola",
    "change_val_field": "Zmień wartość Pola",
    "bind_manager": "Binding Manager",
    "show_binds": "Show binds for selected file",
    "bind_parent": "Bind as Parent to",
    "bind_child": "Bind as Child to",
    "bind_sibling": "Bind as Sibling to",
    "unbind_parent_child": "Unbind as Parent/Child",
    "unbind_sibling": "Unbind as Sibling",
    "show_all_binds": "Show all binds",
    "select_file_item": "Select File from center pan",
    "no_binds": "No binds to show",
    "select_files_to_bind": "Select Files from center pan and right pan",

    "dist_manager": "Dystrybutor",
    "open_in_new_detail_pan": "Otwórz w nowym oknie ",
    "open_file_in_def": "Otwórz Plik",
    "lbl_pan": "Tagi",
    "filter_pan": "Filtrowanie",
    "distr_man": "Dystrybucja",
    "sel_labels": "Wybierz Tag",
    "info_text": """O co tu chodzi?
        Chodzi o utworzenie kombinacji tagów
        Potem program skopiuje wszystkie pliki oznaczone wybranymi tagami to folderów i utworzy raport. 
        Co robić:
        Wybierz Tag(i) i przekaż je dalej do Połaczonych Tagów.
        Sprawdź czy dana kombinacja jest ok i przekaż je dalej do panelu Foldery.
        Uwaga: jeśli kombinacja zawiera dw lub więcej tagów operatorem logiczny między wyrażeniami jest LUB. 
        Zmień nazwy Folderów albo zachowaj nazwy domyślne. Gdy skończysz wybierz Przygotuj Dystrybucję.
        Przed przejściem dalej możesz zapisać wprowadzone kombinacje wybierając Zapisz Schemat.""",
    "push_sel_labels": "Przekaż dalej",
    "save_schema": "Zapisz Schemat",
    "load_schema": "Załaduj Schemat",
    "comb_labels": "Kombinacja Tagów",
    "push_all_lbls_to_folders": "Przekaż dalej wszystkie kombinacje",
    "push_lbl_to_folders": "Przekaż dalej kombinacje",
    "del_comb": "Usuń kombinację",
    "folder": "Folder",
    "rename_folder": "Zmień nazwę folderu",
    "prep_dist": "Przygotuj dystrybucję",
    "del_folder": "Usuń folder",
    "operation_will_affect": "Ta operacja dotyczy Folderu: ",
    "rename_": "Zmień nazwę ",
    "prep_folders_first": "Najpierw przygotuj Foldery",
    "create_files_list": "Utwórz Raport",
    "create_folders_and_files_list": "Utwórz Foldery i Raport",
    "create_folder": "Utwórz Folder",
    "create_report_file": "Utwórz Raport - rozszerzenie xlsx jest zablokowane",
    "files_rep_saved": "Pliki i Raport utworzone!",
    "save_as": "Zapisz jako",
    "rep_saved": "Raport zapisany!",
    "schema_name": "Nazwa Schematu:",
    "del_schema": "Usuń  Schemat",
    "unable_to_save": "Nie można zapisać",
    "schema_exists": "Schemat z tą nazwą już istnieje",
    "distributor": "Distrybutor",

}

LANG_eng = {
    "title": "Personal assistant / Clerk 2.0",
    "new_pro": "Create New Project",
    "open_pro": "Open Project",
    "quit": "Quit",
    "file": "File",
    "sel_dir": "Select Directory",
    "go_back": "Go Back",
    "sel_location": "Select location: ",
    "chang_location": "Change location",
    "new_pro_info": "Create New Project\nChoose the location where you want to set the Project\n(the best idea is to create a new folder in default location)\nRemember that the new folder name will be the name of the Project.",
    "pro_already_created": "Project already created in that location.",
    "pro_already_created_msg": "Delete an existing project in that location and then set a new one.",
    "path_exists": "Path exists.",
    "path_exists_msg": "Do you want to create a project in that location?",
    "wrong_path": "Choose a path to a directory.",
    "wrong_path_msg": "A chosen path leads to a file not to a directory.",
    "wrong_path_name": "Wrong path name.",
    "wrong_path_name_msg": "Wrong path name. Some characters might be not allowed (check: < > : \" / \\ | ? *).",
    "Unable_to_save": "Cannot save initial files in that directory",
    "Unable_to_save_msg": "Some files necessary to set up a project already exist in the directory. Delete them or set up a project in another directory",
    "add_files": "Add files to project",
    "add_folder": "Add Folder with files",
    "sel_project": "Selected project:",
    "browse": "Browse",
    "sel_dir_proj": "Select a directory with a project",
    "add_files_from_dir": "Add files from selected directory",
    "options": "Options",
    "copy_all_files": "Copy all files",
    "copy_only": "Copy only .jpg, .jpeg, .png files. (The rest will be ignored) ",
    "sel_dir_with_files": "Select a directory with files to add",
    "wrong_path_2": "Wrong path",
    "wrong_path_2_msg": "Pass an absolute path, eg. C:\\My documents\\Files...",
    "wrong_path_2_msg_2": "It's not a directory. Do you want to add files from",
    "confirm": "Confirm",
    "confirm_msg": "Copying ready to start. It may last a few minutes depending on the scale.",
    "Files_added": "Files added",
    "Files_added_msg": " file(s) added to the project.",
    "circ_ref": "Circular reference",
    "circ_ref_msg": "A circular reference spotted: You tried to add to the project a directory that contains this project",
    "choose_file": "Choose a file from the list above",
    "Available_formats": "Available formats: .jpg, .jpeg, .png\nTry Open in default viewer",
    "Pass_sources": "Pass sources to add to the project:",
    "look_up": "Look up",


    "settings": "Settings",
    "add_links": "Add Sources",
    "manage_links": "Manage Sources (URLs/Info)",
    "assign_sources": "Assign Sources",
    "input_links": "Paste Links or Descriptions for Screenshots\nNew Line (Enter) Separates Successive Links/Desc",
    "list_files": "List Files",
    "labels": "Labels",
    "del_pro": "Delete Project",
    "filter_labels": "Filter Labels",
    "proj_name": "Project Name:",
    "proj_local": "Project will be saved in:",
    "error": "Error!",
    "wrong_dir_name": "Wrong directory name! No < > : \" / \\ | ? * allowed.",
    "dir_exists": "Dir or file with that name already exists! Try different name.",
    "lack_of_base_file": "It's not a project directory! A directory must include base.json file.",
    "no_files": "No files or directories added to the project.",
    "f_name": "File name",
    "source": "Source",
    "path": "Path",
    "c_time": "Creation time",
    "add_f_copy_files": "Updating project and copying files. I'll let you know when I'm finished :)",
    "update_copy_finish": "Updating project and copying files finished. Total files added: ",
    "no_files_added": "Something went wrong: No files added.",
    "submit": "Submit",
    "no_links_or_wrong": "Wrong links or no links!",
    'source_added': "Total number of sources has been added: ",
    "show_all_links": "Show all sources in the project",
    "show_unassigned_links": "Show only unassigned sources",
    "assign": "Assign Source to Image",
    "mark_sources_and_img": "Mark Source and Image to Assign",
    "ask_assign": "Do you want to assign Source to Image?",
    "ask_save_changes": "Do you want to save changes?",
    "no_changes_applied": "No changes applied. Nothing to save.",
    "save_changes": "Save Changes",
    "del_source": "Delete Source",
    "no_source_sel": "No Source Selected",
    "save_to_confirm_del": "Save to confirm deletion",
    "f_rename": "Rename File",
    "s_rename": "Rename Source",
    "manage_labels": "Manage Labels",
    "comment": "Comment",
    "extra_fields": "Extra Fields",
    "alter_comment": "Alter Comment",
    "del_file": "Delete File",
    "del_file_confirm": "Are you sure you want delete this File (this operation is irreversible and affects binds): ",
    "binds_affected": "Binds affected: ",
    "manage_fields": "Manage Fields",
    "input_new_label": "Input new Label:",
    "add_label": "Add Label",
    "del_label": "Delete Label",
    "edit_label": "Edit Label",
    "no_labels": "Empty string or Label already added",
    "no_label_selected": "No Label selected",
    "ask_del_conf_1": "This operation will affect: ",
    "ask_del_conf_2": " file(s).\nAre you sure you want to delete the Label:\n",
    "rename_label": "Rename Label: ",
    "ask_edit_conf_1": "This operation will affect: ",
    "ask_edit_conf_2": " file(s).\nAre you sure you want to edit the Label:\n",
    "no_new_label_name": "Input a new Label name",
    "label_man": "Label management for: ",
    "sel_lbl": "Select Label",
    "remove_lbl": "Remove Label",
    "confirm_sel": "Save Changes",
    "go_to_labels": "Go to Label Manager",
    "all_lbls": "All Labels in the Project",
    "file_lbls": "Labels related to the File",
    "sel_lbls_incl": "Select Labels to Include",
    "sel_lbls_excl": "Select Labels to Exclude",
    "show_all": "Show all",
    "update": "Update",
    "filter": "Filter",
    "add_field": "Add Field",
    "edit_field": "Edit Field",
    "del_field": "Delete Field",
    "curr_field": "Current Field: ",
    "field_name": "Field name",
    "field_val": "Field value",
    "same_comment": "New Comment looks exactly like the previous one",
    "same_source": "New Source looks exactly like the previous one",
    "same_f_name": "New File name looks exactly like the previous one",
    "f_name_wrong_suffix": "New File name has a different suffix. Keep the same file extension to prevent incompatibility.",
    "fields_manager": "Fields Manager",
    "rename_field": "Rename Field",
    "change_val_field": "Change Field value",
    "bind_manager": "Binding Manager",
    "show_binds": "Show binds for selected file",
    "bind_parent": "Bind as Parent to",
    "bind_child": "Bind as Child to",
    "bind_sibling": "Bind as Sibling to",
    "unbind_parent_child": "Unbind as Parent/Child",
    "unbind_sibling": "Unbind as Sibling",
    "show_all_binds": "Show all binds",
    "select_file_item": "Select File from center pan",
    "no_binds": "No binds to show",
    "select_files_to_bind": "Select Files from center pan and right pan",
    "or_include": "'OR' operator between Labels to include",
    "and_include": "'AND' operator between Labels to include",
    "or_exclude": "'OR' operator between Labels to exclude",
    "and_exclude": "'AND' operator between Labels to exclude",
    "dist_manager": "Distribute Label Manager",
    "open_default_viewer": "Open in default viewer",
    "open_in_new_detail_pan": "Open in new detail pan",
    "move_up": "Move up",
    "move_down": "Move down",
    "open_src_browser": "Open Src in Browser",
    "open_file_in_def": "Open File in Default",
    "add_labels": "Add Label(s)",
    "rem_labels": "Remove Label(s)",
    "file_history": "File History",
    "proj_hist": "Project History",
    "lbl_pan": "Label Pan",
    "filter_pan": "Filter Pan",
    "distr_man": "Distribute",
    "lbls_in_pro": "Labels in the project",
    "add_lbl_to_project": "Add Label to\nthe Project",
    "remane_lbl": "Rename Label",
    "del_lbl": "Delete Label",
    "type_lbl_name": "Type in a new label name:",
    "add_lbl_to_pro": "Add Label to the Project",
    "msg_message_delete": "Are you sure you want to delete ",
    "restore": "Restore",
    "sel_labels": "Select Labels",
    "info_text": """What is all about?
        The main idea is to create combinations of labels. 
        Then the program will copy all files linked to created combinations to dedicated directories and return a report with file's data.
        How it works:
        Select Label(s) and push them to Combined Labels.
        Check if combination is ok and push them to Folders.
        Beware: if a combination consists of at least two labels a logical operator between them is OR.
        Rename Folders or keep default names. If all folders are ready choose Prepare Distribution.
        Before preparing Distribution you can save current settings by choosing Save Schema""",
    "push_sel_labels": "Push selected Labels",
    "save_schema": "Save schema",
    "load_schema": "Load schema",
    "comb_labels": "Combined Labels",
    "push_all_lbls_to_folders": "Push all combined Labels to Folders",
    "push_lbl_to_folders": "Push combined Label to Folders",
    "del_comb": "Delete combination",
    "folder": "Folder",
    "rename_folder": "Rename Folder",
    "prep_dist": "Prepare Distribution",
    "del_folder": "Delete folder",
    "operation_will_affect": "This operation will affect Folder: ",
    "rename_": "Rename ",
    "prep_folders_first": "Prepare Folders first",
    "create_files_list": "Create Files list",
    "create_folders_and_files_list": "Create Folders and Files list",
    "create_folder": "Create folder",
    "create_report_file": "Create Report file - xlsx extension is fixed",
    "files_rep_saved": "Files and Report saved!",
    "save_as": "Save as",
    "rep_saved": "Report saved!",
    "schema_name": "Schema name:",
    "del_schema": "Delete schema",
    "unable_to_save": "Unable to save",
    "schema_exists": "Schema with this name already exists",
    "distributor": "Distributor"
}

LANG = LANG_pl
